# Generated by Django 4.0.4 on 2022-05-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articlemodel',
            table='yuki_web',
        ),
    ]
