# Generated by Django 4.0.4 on 2022-05-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_articlemodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='subtitle',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
