# Generated by Django 4.0.4 on 2022-05-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_articlemodel_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='pageviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
