# Generated by Django 4.0.3 on 2022-05-16 11:17

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('web', '0006_alter_articlemodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
