# Generated by Django 4.0.3 on 2022-05-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_diarymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diarymodel',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelTable(
            name='diarymodel',
            table='yuki_diary',
        ),
    ]
