# Generated by Django 4.0.3 on 2022-05-20 10:55

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_diarymodel_options_alter_diarymodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarymodel',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='diary_img/%Y%m/%Y%m%d%H%M%S'),
        ),
    ]
