# Generated by Django 4.0.3 on 2022-05-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_diarymodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarymodel',
            name='tags',
        ),
    ]
