# Generated by Django 4.0.3 on 2022-05-20 11:32

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_diarymodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarymodel',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='static/diary_img/%Y%m/%Y%m%d%H%M%S'),
        ),
    ]
