# Generated by Django 4.0.3 on 2022-05-29 03:15

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_diarymodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarymodel',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='static/diary_img/%Y%m/%Y%m%d'),
        ),
    ]
