# Generated by Django 4.0.3 on 2022-05-29 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0014_diarymodel_image_thumbnail_alter_diarymodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadMeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='static/diary_img/%Y%m/%Y%m%d')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'yuki_ReadMe',
                'ordering': ('-created',),
            },
        ),
    ]
